### ISSUE TITLE
Thanks for sharing.Feedback problems

### ISSUE THREAD

**Issue by 597579501** [zedoul/ZDStickerView#15]
感谢分享。这个东西确实解决了初学者不会的难题。所需要的功能基本在里面。但是问题还是蛮多的。 开始以为不是我要的东西。但是后面发现。里面考虑的几个属性参数还是挺多的。拉伸是否等比拉伸。是否在父视图布局内等。 但是我发现的几个问题如下 1.旋转手势明显和移动手势有冲突。多重复几次。你会发现你的控件还是偏移了很多。 2.虽然考虑到移动时候是否在父视图布局内。可是你TM的。为什么不考虑旋转的时候呢。。。。。。。 最后还是感谢分享。这个地方卡了我整整一天多。现在基本实现了。只能靠自己优化了。或者哪个大神看到有类似很完美的。记得分享@我一下。谢谢了

Thanks for sharing. This thing does not really solve the problem for beginners. Basic functions needed inside. But the question still find many. I began to think that is not what I want. But later found. Some attribute parameter inside or with a lot of consideration. Whether drawing geometric drawing. Whether in the parent view layout. But I found a few problems as follows 1. Rotate gestures visible and moving gesture conflict. Repeated many times. You will find your control or offset a lot. 2. While considering whether to move when the parent view within the layout. But you (TM). Why not consider the time it rotates. . . . . . . Finally thanks for sharing. The whole day I place the card more. Now the basic realization. We can only rely on their own optimized. Or which Great God see similar very perfect. Remember share @ me. Thank you

**Comment by zedoul** [comment]
Thanks a lot for filing this issue! Also, I am pleased to know this library helps you.

It's a bit hard for me to understand your issue though, but I guess you meant the rotation problems. Would you like to let me know the version / device what you used? Is it reproducible by using simulator as well? I'd be more than happy to know your more detailed feedbacks.

**Comment by zedoul** [comment]
By the way, I am really agreed with you that "it needs to be optimized".
