### ISSUE TITLE
Image keeps rotating while i am trying to resize it to smaller  

### ISSUE THREAD

**Issue by Mousum** [zedoul/ZDStickerView#19]
I am using the module to put sticker on image , so user can make it as small as he wants. But the problem is it starts spinning when user tries to make it smaller. any idea to solve  the issue ?

**Comment by zedoul** [comment]
Thanks for using this module! I am also aware of this issue, but currently I am not maintain this module so far. I think we can try some threshold less than a certain point that makes a unexpected rotation. I would really appreciate if you send me a pull request that fixes this problem.
