### ISSUE TITLE
preventsPositionOutsideSuperview = YES restricts the view unexpectedly

### ISSUE THREAD

**Issue by nfs3250** [zedoul/ZDStickerView#5]
Here is my code
```
   CGRect frame = CGRectMake(50, self.wineLabelImageView.frame.origin.y+10, 100, 50);
    UITextView *textView = [[UITextView alloc] initWithFrame:frame];
    textView.text = @"Sample Text";
    textView.backgroundColor = [UIColor clearColor];
    textView.editable = NO;
    textView.delegate = self;
    textView.textColor = [UIColor greenColor];
    
    ZDStickerView *userResizableView = [[ZDStickerView alloc] initWithFrame:frame];
    userResizableView.tag = 1;
    userResizableView.delegate = self;
    userResizableView.contentView = textView;
    userResizableView.preventsPositionOutsideSuperview = YES;
    userResizableView.preventsCustomButton = NO;
    [userResizableView setButton:ZDSTICKERVIEW_BUTTON_CUSTOM
                           image:[UIImage imageNamed:@"Write.png"]];
    userResizableView.preventsResizing = NO;
    [userResizableView hideEditingHandles];
    [self.containerView addSubview:userResizableView];
```
But when I try to drag the ZDStickerView within my containerView (white colored) , it restricts the ZDStickerView before the actual boundary of container view as shown in below screenshots

![left](https://f.cloud.github.com/assets/647008/1379726/c1e832da-3af6-11e3-97d0-8f493c5960a0.png)

![right](https://f.cloud.github.com/assets/647008/1379729/d7d48eea-3af6-11e3-8f5a-d363303bbb14.png)
![top](https://f.cloud.github.com/assets/647008/1379731/dd9ad08c-3af6-11e3-8d8f-9f1a890f6aa4.png)
![bottom](https://f.cloud.github.com/assets/647008/1379732/e0cfa61a-3af6-11e3-9bb5-df5dbac1988c.png)

Can you tell me whats going wrong in my code ?

**Comment by zedoul** [comment]
It is fixed. Although I am not sure the fix also is going to fix your problem as well. 

Apart from that, I would say I am so sorry since I know it is too late to reply this question. Let me explain, at that time I was under very hard time since I just moved to new country and struggled to survive.
